# Generated by Django 3.1.3 on 2020-11-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidcases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='county',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(max_length=1024, unique=True),
        ),
    ]
